### ISSUE TITLE
Failed to load the image!

### ISSUE THREAD

**Issue by nmghelani** [iamutkarshtiwari/Ananas#28] opened 2019-09-23 17:40 UTC
Every time I selects image, I get failed to load the image!
I've tried many different ways but I didn't get what's the problem. I shared my code please check and let me know if there is any problem in implementation.

        try {
                Intent intent = new ImageEditorIntentBuilder(this, data.getData(), Environment.getExternalStorageDirectory().getAbsolutePath()+"/test.png")
                        .withAddText() // Add the features you need
                        .withFilterFeature()
                        .withRotateFeature()
                        .withCropFeature()
                        .withStickerFeature()
                        .forcePortrait(true)
                        .build();

                EditImageActivity.start((MainActivity) mContext, intent, PHOTO_EDITOR_REQUEST_CODE);
            } catch (Exception e) {
                Log.e(TAG, "onActivityResult: "+e.getMessage() );
            }

**Comment by iamutkarshtiwari** [comment] 2019-09-24 06:28
@nmghelani I appreciate your feedback. Thank you!

I suspect this could be an issue because of either `data.getData()` or `Environment.getExternalStorageDirectory().getAbsolutePath()+"/test.png"` returns an invalid path string.

I would suggest you use logcat, copy the complete logs and share them here. This way we can track down the root cause.

**Comment by iamutkarshtiwari** [comment] 2019-10-25 06:30
I will close this ticket as I didn't get any response yet. Please feel free to re-open if you face the issue again.

**Closed by iamutkarshtiwari** 2019-10-25 06:30 UTC
